In [2]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset.shape
dataset.columns.values

array(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'], dtype=object)

In [5]:
# Importing the dataset
X = dataset.iloc[:, 3: 13].values
y = dataset.iloc[:, 13].values

In [7]:
X1 = dataset.iloc[:, 3: 13]
X1.head(5)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [15]:
onehotencoder = OneHotEncoder(categorical_features = [1]) 
X = onehotencoder.fit_transform(X).toarray() 

C:\Users\Amir\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Amir\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
X[0:5,:]

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
        0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.0800000e+02,
        0.0000000e+00, 4.1000000e+01, 1.0000000e+00, 8.3807860e+04,
        1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 5.0200000e+02,
        0.0000000e+00, 4.2000000e+01, 8.0000000e+00, 1.5966080e+05,
        3.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.1393157e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.9900000e+02,
        0.0000000e+00, 3.9000000e+01, 1.0000000e+00, 0.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 0.0000000e+00, 9.3826630e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 8.5000000e+02,
        0.0000000e+00, 4.3000000e+01, 2.0000000e+00, 1.2551082e+05,
        1.0000000e+00, 1.0000000e+00, 1.0000

In [17]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder() 
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

onehotencoder = OneHotEncoder(categorical_features = [1]) 
X = onehotencoder.fit_transform(X).toarray() 
# remove extra dummy variable
X = X[:,1:] 

C:\Users\Amir\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Amir\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [18]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
X_test

array([[ 1.75486502, -1.01460667, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 ,  0.98560362, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 , -1.01460667,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 , -1.01460667,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -1.01460667, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -1.01460667, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [21]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [29]:
# first step: create a Sequential object, as a sequence of layers. B/C NN is a sequence of layers.
classifier = Sequential()

In [30]:
# add the first hidden layer
classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))

In [31]:
# add the second hidden layer
classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))

In [32]:
# add the output layer
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',
                    activation = 'sigmoid'))

In [33]:
# compiling the NN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [34]:
# train the model
classifier.fit(X_train,y_train,batch_size=10,epochs=20)

Epoch 1/20
8000/8000 [==============================] - 1s 119us/step - loss: 0.5767 - acc: 0.7011
Epoch 2/20
8000/8000 [==============================] - 1s 76us/step - loss: 0.4341 - acc: 0.8097
Epoch 3/20
8000/8000 [==============================] - 1s 74us/step - loss: 0.4034 - acc: 0.8240
Epoch 4/20
8000/8000 [==============================] - 1s 75us/step - loss: 0.3809 - acc: 0.8379
Epoch 5/20
8000/8000 [==============================] - 1s 76us/step - loss: 0.3643 - acc: 0.8460
Epoch 6/20
8000/8000 [==============================] - 1s 78us/step - loss: 0.3565 - acc: 0.8511
Epoch 7/20
8000/8000 [==============================] - 1s 74us/step - loss: 0.3520 - acc: 0.8529
Epoch 8/20
8000/8000 [==============================] - 1s 77us/step - loss: 0.3485 - acc: 0.8552
Epoch 9/20
8000/8000 [==============================] - 1s 76us/step - loss: 0.3457 - acc: 0.8554
Epoch 10/20
8000/8000 [==============================] - 1s 77us/step - loss: 0.3429 - acc: 0.8586
Epoch 11/20
8000/8

In [35]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [36]:
y_pred

array([[0.2859527 ],
       [0.31269076],
       [0.1914581 ],
       ...,
       [0.13833997],
       [0.14131716],
       [0.22978029]], dtype=float32)

In [37]:
y_pred = (y_pred>0.5)

In [38]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [39]:
cm

array([[1513,   82],
       [ 194,  211]], dtype=int64)

In [40]:
(1513+211)/2000

0.862

In [41]:
# k-fold clustering
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [42]:
def build_classifier():
    # first step: create a Sequential object, as a sequence of layers. B/C NN is a sequence of layers.
    classifier = Sequential()
    # add the first hidden layer
    classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))
    # add the second hidden layer
    classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))
    # add the output layer
    classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',
                    activation = 'sigmoid'))
    # compiling the NN
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [46]:
classifier = KerasClassifier(build_fn=build_classifier, batch_size = 10, nb_epoch = 3)
accuracies = cross_val_score(estimator=classifier, X=X_train, y = y_train, cv=10, n_jobs=1)

Epoch 1/1
800/800 [==============================] - 0s 387us/step
Epoch 1/1
800/800 [==============================] - 0s 391us/step
Epoch 1/1
800/800 [==============================] - 0s 399us/step
Epoch 1/1
800/800 [==============================] - 0s 424us/step
Epoch 1/1
800/800 [==============================] - 0s 453us/step
Epoch 1/1
800/800 [==============================] - 0s 476us/step
Epoch 1/1
800/800 [==============================] - 0s 466us/step
Epoch 1/1
800/800 [==============================] - 0s 519us/step
Epoch 1/1
800/800 [==============================] - 0s 531us/step
Epoch 1/1
800/800 [==============================] - 0s 553us/step


In [47]:
accuracies.mean()

0.7968749965727329

In [48]:
accuracies.std()

0.013314113096523448

In [79]:
# Drop Out Regularization
# You can detect overfitting with the difference between test and train error or the high variance in cross-validation.

from keras.layers import Dropout

# first step: create a Sequential object, as a sequence of layers. B/C NN is a sequence of layers.
classifier = Sequential()
# add the first hidden layer
classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))
classifier.add(Dropout(p=0.1))  #often start with 0.1, not solved go up

# add the second hidden layer
classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))
classifier.add(Dropout(p=0.1))  #often start with 0.1, not solved go up

# add the output layer
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',
                    activation = 'sigmoid'))
# compiling the NN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

C:\Users\Amir\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Amir\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:16: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  app.launch_new_instance()


In [87]:
# fine tuning with Grid Search
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

def build_classifier(optimizer):
    # first step: create a Sequential object, as a sequence of layers. B/C NN is a sequence of layers.
    classifier = Sequential()
    # add the first hidden layer
    classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))
    # add the second hidden layer
    classifier.add(Dense(units=6,kernel_initializer='glorot_uniform',
                    activation = 'relu'))
    # add the output layer
    classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',
                    activation = 'sigmoid'))
    # compiling the NN
    classifier.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [88]:
classifier = KerasClassifier(build_fn=build_classifier)

# create a dictionary of hyper-parameters to optimize
parameters = {'batch_size':[25,32], 'nb_epoch':[1,2],'optimizer':['adam','rmsprop']}
grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv=10)
grid_search = grid_search.fit(X_train,y_train)

best_parameters = grid_search.best_params_ 
best_accuracy = grid_search.best_score_

Epoch 1/1
7200/7200 [==============================] - 4s 567us/step - loss: 0.5074 - acc: 0.7939
Epoch 1/1
7200/7200 [==============================] - 4s 556us/step - loss: 0.5723 - acc: 0.7396
Epoch 1/1
7200/7200 [==============================] - 4s 571us/step - loss: 0.5603 - acc: 0.7893
Epoch 1/1
7200/7200 [==============================] - 4s 564us/step - loss: 0.6160 - acc: 0.7450
Epoch 1/1
7200/7200 [==============================] - 4s 583us/step - loss: 0.6451 - acc: 0.6272
Epoch 1/1
7200/7200 [==============================] - 4s 596us/step - loss: 0.5681 - acc: 0.7547
Epoch 1/1
7200/7200 [==============================] - 4s 593us/step - loss: 0.5736 - acc: 0.7278
Epoch 1/1
7200/7200 [==============================] - 4s 613us/step - loss: 0.5557 - acc: 0.7628
Epoch 1/1
7200/7200 [==============================] - 5s 646us/step - loss: 0.6023 - acc: 0.7082
Epoch 1/1
7200/7200 [==============================] - 5s 691us/step - loss: 0.5403 - acc: 0.7646
Epoch 1/1
7200/7200 

KeyboardInterrupt: 